package com.ruijie.cloud.macc.dataplatform.metadata.datasource.jdbc;

public class PhoenixMetaDataQueryConstant {
	public static final String ALL_TABLE_PRIMARY_KEY_SQL =
			"SELECT COLUMN_NAME, TABLE_NAME, KEY_SEQ FROM SYSTEM.CATALOG WHERE TABLE_SCHEM = ? AND COLUMN_FAMILY IS NULL AND KEY_SEQ IS NOT NULL ORDER BY KEY_SEQ";

	public static final String GET_PHOENIX_TABLE_PRIMARY_KEY_SQL = "SELECT COLUMN_NAME FROM SYSTEM.CATALOG "
			+ "WHERE TABLE_SCHEM = ? AND TABLE_NAME = ? AND COLUMN_FAMILY IS NULL " + "AND KEY_SEQ IS NOT NULL "
			+ "ORDER BY KEY_SEQ";
	public static final String GET_PHOENIX_INDEX_COlUMN_NAMES = "SELECT COLUMN_NAME FROM SYSTEM.CATALOG "
			+ "WHERE TABLE_SCHEM = ? AND TABLE_NAME = ? AND COLUMN_NAME IS NOT NULL " + "ORDER BY KEY_SEQ, COLUMN_NAME";
	public static final String GET_PHOENIX_TABLE_INDEX =
			"SELECT DISTINCT TABLE_NAME AS INDEX_NAME, DATA_TABLE_NAME, INDEX_TYPE " + "FROM SYSTEM.CATALOG "
					+ "WHERE TABLE_SCHEM = ? AND DATA_TABLE_NAME = ? AND TABLE_TYPE = 'i'";
}
